- .github/workflows/main.yml
> feat: upgrade ci node to 16 (lts)

- package-lock.json
- package.json
> Rm packages

- package-lock.json
- src/apis/Interviews.ts
- src/components/common/tab-panel.tsx
- src/components/games/Menu.tsx
- src/components/games/Routes.tsx
- src/components/games/family-feud/FamilyFeud.test.tsx
- src/components/games/family-feud/FamilyFeud.tsx
- src/components/games/family-feud/FastMoney.tsx
- src/components/games/family-feud/FastMoneyTable.tsx
- src/components/games/family-feud/GameRound.tsx
- src/components/games/family-feud/TeamsDisplay.tsx
- src/components/games/family-feud/helpers.ts
- src/components/games/family-feud/index.ts
- src/constants/cars.ts
> feat: add local family feud

- .npmrc
- package-lock.json
- package.json
- src/components/resume/cars/tests/CarChart.test.tsx
- src/components/resume/cars/tests/Cars.test.tsx
- src/components/resume/work/tests/Work.test.tsx
> fix: npm errors

- .github/workflows/main.yml
- package-lock.json
- package.json
- package.md
> test: install pkgs as dev deps

- public/manifest.json
> fix: update theme

- .github/workflows/main.yml
- lighthouserc.json
> feat: add lighthouse gh action

- src/components/resume/Menu.tsx
> feat: add menu icons for external links

- src/wrappers/WithTheme.tsx
> fix: wcag 2.1 AA compliance for theme colors

- src/components/common/header/TopBar.tsx
- src/components/games/Home.tsx
- src/components/resume/Menu.tsx
> fix: some a11y issues found by evinced

- package-lock.json
> fix: npm audit fix

- src/components/games/are-you-the-one/AreYouTheOne.test.tsx
- src/components/games/are-you-the-one/AreYouTheOne.tsx
- src/components/games/are-you-the-one/Controls.tsx
- src/recoil/are-you-the-one-atom.ts
> fix: ayto default and blackout updates

- package-lock.json
- package.json
- src/components/common/expandable-card/ExpandableCard.test.tsx
- src/components/common/timeline-card/tests/Segment.test.tsx
- src/components/common/timeline-card/tests/TimelineCard.test.tsx
- src/components/games/connect4/Connect4.test.tsx
- src/components/resume/git-tools/tests/CommitText.test.tsx
- src/components/resume/git-tools/tests/DeployBranch.test.tsx
- src/components/resume/git-tools/tests/Header.test.tsx
> feat: update vitest

- .gitignore
- package-lock.json
- package.json
- src/constants/cars.ts
> test: enhance codecov functionality (that was lost)

- src/constants/cars.ts
> fix: car consts

- package-lock.json
- src/components/resume/travel-map/tests/CountryTable.test.tsx
- src/constants/travel.ts
> feat: add upcoming countries to travel map

- src/components/games/deal-or-no-deal/DealOrNoDeal.tsx
- src/components/games/slots/Slots.tsx
- src/components/games/yahtzee/Yahtzee.tsx
- src/components/games/yahtzee/use-yahtzee-state.ts
- src/recoil/deal-or-no-deal-state.ts
- src/recoil/slots-state.ts
- src/recoil/yahtzee-state.ts
> fix: readonly data to readonly selectors

- package-lock.json
- package.json
- renovate.json
> fix: remove c8 package

- package.json
- package.md
> fix: minor package stuff

- index.html
- tsconfig.json
- vite.config.ts
> fix: changes for codesandbox

- src/components/games/blackjack/Rules.tsx
- src/components/games/blackjack/help/BlackjackTable.tsx
- src/components/games/blackjack/help/Help.tsx
- src/components/games/blackjack/help/Row.tsx
- src/components/games/murder-mystery/MurderMysteryPanel.tsx
- src/components/games/slots/MoneyTable.tsx
- src/components/games/slots/PayoutTable.tsx
- src/components/games/slots/ReelDisplay.tsx
- src/components/games/tictactoe/Board.tsx
- src/components/games/type-checker/EffectiveRow.tsx
- src/components/games/type-checker/TypeChecker.tsx
- src/components/games/yahtzee/score-table/BottomScores.tsx
- src/components/games/yahtzee/score-table/BottomTable.tsx
- src/components/games/yahtzee/score-table/ScoreTable.tsx
- src/components/games/yahtzee/score-table/TopScores.tsx
- src/components/games/yahtzee/score-table/TopTable.tsx
- src/components/resume/summary/Info.tsx
- src/components/resume/travel-map/CountryTable.tsx
- src/components/resume/travel-map/CruiseTable.tsx
> fix: table a11y

- .github/workflows/main.yml
> fix: upgrade node version in github ci

- src/components/resume/cars/CarChart.tsx
- src/components/resume/cars/CarSankeyGraph.tsx
- src/components/resume/travel-map/CruiseCharts.tsx
- src/components/resume/travel-map/WorldMap.tsx
- src/constants/cars.ts
> fix: add highcharts accessibility

- src/components/resume/cars/CurrentCarStats.tsx
- src/components/resume/cars/CurrentCarStatsGraph.tsx
- src/constants/cars.ts
> feat: hard code green/red segments on speedos

- src/components/resume/travel-map/cruises/LoyaltyCharts.tsx
- src/constants/cruises.ts
> fix: cruise loyalty charts

- package-lock.json
- package.json
> fix: update gts

- .eslintrc.json
> fix: remove rest of airbnb code

- src/components/games/botc/character-sheet/Roles.tsx
> fix: logic in botc script page

- eslint.config.js
> fix: cleanup eslint

- eslint.config.js
- src/apis/Deck.ts
- src/components/common/header/TopBar.tsx
- src/components/games/are-you-the-one/AreYouTheOne.tsx
- src/components/games/are-you-the-one/histogram/useHist.ts
- src/components/games/botc/player-notes/character-sheet/Roles.tsx
- src/components/games/family-feud/GameRound.tsx
- src/components/games/game-table/board/card/Card.tsx
- src/components/games/game-table/board/player/Player.tsx
- src/components/games/poker/Poker.tsx
- src/components/games/poker/helpers.ts
- src/components/games/tictactoe/History.tsx
- src/constants/cars.ts
- src/constants/work.ts
> fix: no unused expressions

- src/components/games/Routes.tsx
- src/components/resume/Routes.tsx
> fix: rebase simplification

- src/components/resume/comp-calc/CompCalculator.tsx
- src/components/resume/comp-calc/CompGraph.tsx
> feat: add stock backup if stockAdj not def

- src/constants/cars.ts
> feat: update car info

- package-lock.json
- package.json
- src/components/Routes.tsx
- src/wrappers/WithRouter.tsx
> fix: react router upgrade

- src/components/resume/cars/CarChartControls.tsx
- src/components/resume/cars/CarDisplay.tsx
- src/components/resume/cars/Cars.tsx
- src/components/resume/cars/graphs/CarChart.tsx
- src/components/resume/cars/graphs/CarGraphs.tsx
- src/components/resume/cars/graphs/CarSankeyGraph.tsx
- src/components/resume/cars/graphs/CurrentCarStats.tsx
- src/components/resume/cars/graphs/CurrentCarStatsGraph.tsx
- src/constants/cars.ts
> fix: optimize cars for ultra wide screens

- package-lock.json
- package.json
- src/components/resume/cars/graphs/CarChart.tsx
- src/components/resume/cars/graphs/CarSankeyGraph.tsx
- src/components/resume/cars/graphs/CurrentCarStatsGraph.tsx
- src/components/resume/comp-calc/graphs/BreakdownGraph.tsx
- src/components/resume/comp-calc/graphs/CompGraph.tsx
- src/components/resume/travel-map/cruises/CruiseCharts.tsx
- src/components/resume/travel-map/cruises/LoyaltyCharts.tsx
- src/components/resume/travel-map/map/WorldMap.tsx
> fix: upgrade highcharts major version

- src/components/games/spades/useSpades.ts
> feat: enhance overbid tracker

- src/constants/cars.ts
> fix: car sankey graphs

- src/App.test.tsx
- src/components/Routes.tsx
- src/components/common/header/tests/Header.test.tsx
- src/components/common/header/tests/PlayerMenu.test.tsx
- src/components/common/info-popover/InfoPopup.test.tsx
- src/components/resume/Menu.test.tsx
- src/components/resume/Menu.tsx
> feat: improve code-cov

- src/components/common/edu-cards/Year.tsx
- src/components/games/imperial-assault/Empire.tsx
- src/constants/cars.ts
- src/constants/classes.ts
> feat: update car graphs visability

- src/components/resume/cars/CarChartControls.tsx
- src/components/resume/cars/Cars.tsx
- src/components/resume/cars/graphs/CarGraphs.tsx
- src/components/resume/cars/graphs/CurrentCarStats.tsx
- src/components/resume/cars/tests/Cars.test.tsx
- src/constants/cars.ts
> feat: remove cars duplications

- package-lock.json
- package.json
- src/apis/DateHelper.ts
- src/components/common/expandable-card/ExpandableCard.tsx
- src/components/common/header/TopBar.tsx
- src/components/resume/cars/graphs/CarGraphs.tsx
- src/components/resume/cars/graphs/CarSpeedoGraph.tsx
- src/components/resume/cars/graphs/CurrentCarStats.tsx
- src/components/resume/travel-map/cruises/CruiseTable.tsx
- src/constants/cars.ts
- src/constants/cruises.ts
> feat: update travel display and car display

- src/components/games/imperial-assault/TierLists.tsx
- src/constants/cars.ts
> fix: reduce tier columns

- package-lock.json
- src/components/games/spades/useSpades.ts
> fix: var naming and sec updates

- src/components/games/spades/Spades.test.tsx
- src/components/games/spades/control-bar/AddScorePlayer.tsx
- src/components/games/spades/control-bar/StatsNilsChart.tsx
- src/components/games/spades/useSpades.ts
- src/jotai/spades-atom.ts
> fix: some variables

- package-lock.json
- package.json
- src/setupTests.ts
> feat: upgrade highcharts

- src/components/games/are-you-the-one/AreYouTheOne.test.tsx
- src/components/games/imperial-assault/ImperialAssault.test.tsx
- src/components/games/spades/Spades.test.tsx
- src/components/games/spades/control-bar/StatsBagsChart.tsx
- src/components/games/spades/control-bar/StatsNilsChart.tsx
- src/components/games/spades/helpers.ts
- src/components/resume/cars/graphs/CarChart.tsx
- src/components/resume/cars/graphs/CarSankeyGraph.tsx
- src/components/resume/cars/graphs/CarSpeedoGraph.tsx
- src/components/resume/comp-calc/graphs/BreakdownGraph.tsx
- src/components/resume/comp-calc/graphs/CompGraph.tsx
- src/components/resume/travel-map/cruises/CruiseCharts.tsx
- src/components/resume/travel-map/cruises/LoyaltyCharts.tsx
- src/components/resume/travel-map/map/WorldMap.tsx
> test: increase coverage

- package-lock.json
- package.json
- src/components/resume/travel-map/tests/TravelMap.test.tsx
- src/constants/travel.ts
- vite.config.ts
> feat: update vite

- src/components/common/edu-cards/Year.tsx
- src/components/resume/comp-calc/CompCalculator.test.tsx
- vite.config.ts
> fix: increase test time

- lighthouserc.json
- src/constants/cars.ts
- src/constants/travel.ts
> feat: minor wording fixes

- src/constants/cars.ts
> fix: car sort

- src/components/resume/travel-map/cruises/LoyaltyCharts.tsx
- src/constants/cruises.ts
> feat: update names to flags and add nat geo

- package-lock.json
- src/components/resume/cars/timeline-card/timelineHelpers.ts
> fix: minor timeline tweaks and pkg fix

- src/constants/cruises.ts
> feat: update travel
